package modelo.Entidades;
// Generated May 14, 2019 9:15:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Characteristics generated by hbm2java
 */
@Entity
@Table(name="characteristics"
    ,catalog="proyecto"
)
public class Characteristics  implements java.io.Serializable {


     private Integer id;
     private Products products;
     private int ram;
     private int disk;
     private String processor;
     private String screen;

    public Characteristics() {
    }

    public Characteristics(Products products, int ram, int disk, String processor, String screen) {
       this.products = products;
       this.ram = ram;
       this.disk = disk;
       this.processor = processor;
       this.screen = screen;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    
    @Column(name="RAM", nullable=false)
    public int getRam() {
        return this.ram;
    }
    
    public void setRam(int ram) {
        this.ram = ram;
    }

    
    @Column(name="Disk", nullable=false)
    public int getDisk() {
        return this.disk;
    }
    
    public void setDisk(int disk) {
        this.disk = disk;
    }

    
    @Column(name="processor", nullable=false, length=45)
    public String getProcessor() {
        return this.processor;
    }
    
    public void setProcessor(String processor) {
        this.processor = processor;
    }

    
    @Column(name="screen", nullable=false, length=45)
    public String getScreen() {
        return this.screen;
    }
    
    public void setScreen(String screen) {
        this.screen = screen;
    }




}


