package modelo.Entidades;
// Generated May 14, 2019 9:15:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name="inventory"
    ,catalog="proyecto"
)
public class Inventory  implements java.io.Serializable {


     private Integer id;
     private Products products;
     private String sku;
     private float cost;
     private int quantity;
     private Date datePurchase;

    public Inventory() {
    }

    public Inventory(Products products, String sku, float cost, int quantity, Date datePurchase) {
       this.products = products;
       this.sku = sku;
       this.cost = cost;
       this.quantity = quantity;
       this.datePurchase = datePurchase;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    
    @Column(name="sku", nullable=false, length=45)
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }

    
    @Column(name="cost", nullable=false, precision=12, scale=0)
    public float getCost() {
        return this.cost;
    }
    
    public void setCost(float cost) {
        this.cost = cost;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_purchase", nullable=false, length=10)
    public Date getDatePurchase() {
        return this.datePurchase;
    }
    
    public void setDatePurchase(Date datePurchase) {
        this.datePurchase = datePurchase;
    }




}


