package modelo.Entidades;
// Generated May 14, 2019 9:15:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="proyecto"
)
public class Products  implements java.io.Serializable {


     private Integer id;
     private Categories categories;
     private Model model;
     private String productName;
     private float price;
     private String status;
     private int likeCount;
     private Set<Characteristics> characteristicses = new HashSet<Characteristics>(0);
     private Set<Inventory> inventories = new HashSet<Inventory>(0);

    public Products() {
    }

	
    public Products(Categories categories, Model model, String productName, float price, String status, int likeCount) {
        this.categories = categories;
        this.model = model;
        this.productName = productName;
        this.price = price;
        this.status = status;
        this.likeCount = likeCount;
    }
    public Products(Categories categories, Model model, String productName, float price, String status, int likeCount, Set<Characteristics> characteristicses, Set<Inventory> inventories) {
       this.categories = categories;
       this.model = model;
       this.productName = productName;
       this.price = price;
       this.status = status;
       this.likeCount = likeCount;
       this.characteristicses = characteristicses;
       this.inventories = inventories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_model", nullable=false)
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }

    
    @Column(name="product_name", nullable=false, length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="price", nullable=false, precision=12, scale=0)
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }

    
    @Column(name="status", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="like_count", nullable=false)
    public int getLikeCount() {
        return this.likeCount;
    }
    
    public void setLikeCount(int likeCount) {
        this.likeCount = likeCount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<Characteristics> getCharacteristicses() {
        return this.characteristicses;
    }
    
    public void setCharacteristicses(Set<Characteristics> characteristicses) {
        this.characteristicses = characteristicses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<Inventory> getInventories() {
        return this.inventories;
    }
    
    public void setInventories(Set<Inventory> inventories) {
        this.inventories = inventories;
    }




}


