package modelo.Entidades;
// Generated May 14, 2019 9:15:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usr generated by hbm2java
 */
@Entity
@Table(name="usr"
    ,catalog="proyecto"
)
public class Usr  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String nombre;
     private String apellido;
     private String clave;

    public Usr() {
    }

    public Usr(String login, String nombre, String apellido, String clave) {
       this.login = login;
       this.nombre = nombre;
       this.apellido = apellido;
       this.clave = clave;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="login", nullable=false, length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="Nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=50)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Clave", nullable=false, length=100)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


